// Code generated by pgc. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
)

// DBTX is the subset of database/sql methods the generated queries need.
// Both *sql.DB and *sql.Tx satisfy it, so the same Queries value works
// inside and outside a transaction.
type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// Queries exposes one method per SQL query. Create it once with New and
// share it: the value is immutable and safe for concurrent use.
type Queries struct {
	db DBTX
}

// New returns a Queries bound to db, which is usually *sql.DB.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a copy of q that runs its queries inside tx.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
