// Code generated by pgc. DO NOT EDIT.
// Source: queries/q.sql

package store

import "context"

const createUser = `
INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING *
`

// CreateUser runs the query and returns one row. It returns sql.ErrNoRows
// when no row matches.
func (q *Queries) CreateUser(ctx context.Context, email, passwordHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email, passwordHash)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	return u, err
}

const userByEmail = `
SELECT * FROM users WHERE email = $1
`

// UserByEmail runs the query and returns one row. It returns sql.ErrNoRows
// when no row matches.
func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	return u, err
}

const userByID = `
SELECT * FROM users WHERE id = $1
`

// UserByID runs the query and returns one row. It returns sql.ErrNoRows
// when no row matches.
func (q *Queries) UserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	return u, err
}

const createNote = `
INSERT INTO notes (user_id, title) VALUES ($1, $2) RETURNING *
`

// CreateNote runs the query and returns one row. It returns sql.ErrNoRows
// when no row matches.
func (q *Queries) CreateNote(ctx context.Context, userID int64, title string) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, userID, title)
	var n Note
	err := row.Scan(&n.ID, &n.UserID, &n.Title, &n.CreatedAt)
	return n, err
}

const notesByUser = `
SELECT * FROM notes WHERE user_id = $1 ORDER BY id DESC
`

// NotesByUser runs the query and returns the matching rows.
func (q *Queries) NotesByUser(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, notesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var notesByUser []Note
	for rows.Next() {
		var n Note
		if err := rows.Scan(&n.ID, &n.UserID, &n.Title, &n.CreatedAt); err != nil {
			return nil, err
		}
		notesByUser = append(notesByUser, n)
	}
	return notesByUser, rows.Err()
}
