// Code generated by pgc. DO NOT EDIT.

package store

import "time"

// Note mirrors one row of the notes table.
type Note struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Tags      []string  `json:"tags"`
	CreatedAt time.Time `json:"created_at"`
}
