// Code generated by pgc. DO NOT EDIT.
// Source: queries/notes.sql

package store

import "context"

const createNote = `
INSERT INTO notes (title, body, tags) VALUES ($1, $2, $3) RETURNING *
`

// CreateNote inserts a note and returns the whole row, with the generated
// id and timestamp.
func (q *Queries) CreateNote(ctx context.Context, title, body string, tags []string) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, title, body, stringArray(tags))
	var n Note
	err := row.Scan(&n.ID, &n.Title, &n.Body, (*stringArray)(&n.Tags), &n.CreatedAt)
	return n, err
}

const noteByID = `
SELECT * FROM notes WHERE id = $1
`

// NoteByID returns one note by primary key.
func (q *Queries) NoteByID(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, noteByID, id)
	var n Note
	err := row.Scan(&n.ID, &n.Title, &n.Body, (*stringArray)(&n.Tags), &n.CreatedAt)
	return n, err
}

const listNotes = `
SELECT * FROM notes ORDER BY id DESC LIMIT $1
`

// ListNotes lists notes, newest first, with a limit.
func (q *Queries) ListNotes(ctx context.Context, limit int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var notes []Note
	for rows.Next() {
		var n Note
		if err := rows.Scan(&n.ID, &n.Title, &n.Body, (*stringArray)(&n.Tags), &n.CreatedAt); err != nil {
			return nil, err
		}
		notes = append(notes, n)
	}
	return notes, rows.Err()
}

const countNotes = `
SELECT count(*) FROM notes
`

// CountNotes total number of notes.
func (q *Queries) CountNotes(ctx context.Context) (*int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes)
	var v *int64
	err := row.Scan(&v)
	return v, err
}

const searchNotes = `
SELECT * FROM notes WHERE title ILIKE '%' || $1 || '%' ORDER BY id DESC
`

// SearchNotes case-insensitive title search.
func (q *Queries) SearchNotes(ctx context.Context, arg1 string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotes, arg1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var notes []Note
	for rows.Next() {
		var n Note
		if err := rows.Scan(&n.ID, &n.Title, &n.Body, (*stringArray)(&n.Tags), &n.CreatedAt); err != nil {
			return nil, err
		}
		notes = append(notes, n)
	}
	return notes, rows.Err()
}
