// Code generated by pgc. DO NOT EDIT.

package store

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

// pgArrayElems decodes the text form of a one-dimensional PostgreSQL array
// into raw element strings. It returns (nil, nil) for SQL NULL. NULL
// elements and multidimensional arrays are rejected: map the column to a
// plain string with an override when you need to carry them.
func pgArrayElems(src any, who string) ([]string, error) {
	var s string
	switch v := src.(type) {
	case nil:
		return nil, nil
	case []byte:
		s = string(v)
	case string:
		s = v
	default:
		return nil, fmt.Errorf("%s: cannot scan %T", who, src)
	}
	if strings.HasPrefix(s, "[") {
		return nil, fmt.Errorf(
			"%s: arrays with explicit bounds are not supported", who)
	}
	if len(s) < 2 || s[0] != '{' || s[len(s)-1] != '}' {
		return nil, fmt.Errorf("%s: malformed array %q", who, s)
	}
	body := s[1 : len(s)-1]
	if body == "" {
		return []string{}, nil
	}

	var elems []string
	var cur strings.Builder
	quoted, wasQuoted := false, false
	flush := func() error {
		e := cur.String()
		if !wasQuoted {
			e = strings.TrimSpace(e)
			if strings.EqualFold(e, "null") {
				return fmt.Errorf(
					"%s: the array has a NULL element; map the column to "+
						"string with an override to handle it", who)
			}
		}
		elems = append(elems, e)
		cur.Reset()
		wasQuoted = false
		return nil
	}
	for i := 0; i < len(body); i++ {
		c := body[i]
		switch {
		case quoted:
			if c == '\\' && i+1 < len(body) {
				i++
				cur.WriteByte(body[i])
			} else if c == '"' {
				quoted = false
			} else {
				cur.WriteByte(c)
			}
		case c == '"':
			quoted = true
			wasQuoted = true
		case c == '{':
			return nil, fmt.Errorf(
				"%s: multidimensional arrays are not supported", who)
		case c == ',':
			if err := flush(); err != nil {
				return nil, err
			}
		default:
			cur.WriteByte(c)
		}
	}
	if err := flush(); err != nil {
		return nil, err
	}
	return elems, nil
}

// pgQuoteElem renders one string element of an array literal. Every element
// is quoted: unquoted, the server trims surrounding whitespace - newlines and
// form feeds included - and reads NULL as a null, so only the quoted form
// carries the bytes through unchanged.
func pgQuoteElem(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		if s[i] == '"' || s[i] == '\\' {
			b.WriteByte('\\')
		}
		b.WriteByte(s[i])
	}
	b.WriteByte('"')
	return b.String()
}

// stringArray adapts []string to a PostgreSQL text-like[] column or parameter.
type stringArray []string

// Scan implements sql.Scanner for the one-dimensional text format.
func (a *stringArray) Scan(src any) error {
	elems, err := pgArrayElems(src, "stringArray")
	if err != nil || elems == nil {
		*a = nil
		return err
	}
	out := make([]string, len(elems))
	for i, e := range elems {
		out[i] = e
	}
	*a = out
	return nil
}

// Value implements driver.Valuer, encoding the text form; a nil slice is
// SQL NULL.
func (a stringArray) Value() (driver.Value, error) {
	if a == nil {
		return nil, nil
	}
	parts := make([]string, len(a))
	for i, v := range a {
		if strings.IndexByte(v, 0) >= 0 {
			return nil, fmt.Errorf(
				"stringArray: element %d holds a NUL byte, which PostgreSQL text cannot store", i)
		}
		parts[i] = pgQuoteElem(v)
	}
	return "{" + strings.Join(parts, ",") + "}", nil
}
